project:
  type: book

book:
  title: "All of Business"
  author: "Ahmed H. Darwish"
  
  
  navbar:
    title: false
    search: true
    logo: cover.png
      
  chapters:
    - index.qmd
    - chapter01.qmd
    - chapter02.qmd
    - chapter03.qmd
    - chapter04.qmd
    - chapter05.qmd
    - chapter06.qmd
    - chapter07.qmd
    - chapter08.qmd
    - chapter09.qmd
    - chapter10.qmd
    - chapter11.qmd
    - chapter12.qmd
    - chapter13.qmd
    - chapter14.qmd
    - chapter15.qmd
    - chapter16.qmd
    - chapter17.qmd
    - chapter18.qmd
    - chapter19.qmd
    - chapter20.qmd
    - chapter21.qmd
    - chapter22.qmd
    - chapter23.qmd
    - chapter24.qmd
    - chapter25.qmd
    - chapter26.qmd
    - chapter27.qmd
    - chapter28.qmd
    - chapter29.qmd
    - chapter30.qmd


format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    sidebar:
      style: floating