<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>15&nbsp; Venture Deals – All of Business</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./chapter16.html" rel="next">
<link href="./chapter14.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-00ccf60c28c3bdf2d57f5131fbf16f11.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-7c8ba9dac8feea6a77ed63b2e2898d0e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-00ccf60c28c3bdf2d57f5131fbf16f11.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
        <div class="quarto-navbar-tools tools-end">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./chapter15.html"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Venture Deals</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Entrepreuership Theory</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Measure What Matters</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Running Lean</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Four Steps to Successful Strategy</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Power of Emotional Intelligence</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Primal Leadership</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Project Management</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">PMBOK</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Principles of Marketing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">AI Marketing Canvas</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">This is Marketing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Business Development</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Sales Acceleration Formula</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Financial Intelligence for Entrepreneurs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter15.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Venture Deals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter16.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Emotional Agility</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter17.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Emotional Intelligence 2.0</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter18.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Getting Things Done</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter19.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Deep Work</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter20.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Strategic Connections</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter21.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">The Start Up of You</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter22.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">HR Transformation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter23.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Redesigning Work</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter24.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Blitz Scaling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter25.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Scaling Up</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter26.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Corportate Sustainability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter27.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Green to Gold</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#executive-summary-critical-takeaways" id="toc-executive-summary-critical-takeaways" class="nav-link active" data-scroll-target="#executive-summary-critical-takeaways"><span class="header-section-number">15.1</span> <strong>Executive Summary: Critical Takeaways</strong></a></li>
  <li><a href="#the-players" id="toc-the-players" class="nav-link" data-scroll-target="#the-players"><span class="header-section-number">15.2</span> <strong>The Players</strong></a>
  <ul class="collapse">
  <li><a href="#the-entrepreneur-founder" id="toc-the-entrepreneur-founder" class="nav-link" data-scroll-target="#the-entrepreneur-founder"><span class="header-section-number">15.2.1</span> <strong>The Entrepreneur (Founder)</strong></a></li>
  <li><a href="#the-venture-capitalist-vc" id="toc-the-venture-capitalist-vc" class="nav-link" data-scroll-target="#the-venture-capitalist-vc"><span class="header-section-number">15.2.2</span> <strong>The Venture Capitalist (VC)</strong></a></li>
  <li><a href="#financing-round-nomenclature" id="toc-financing-round-nomenclature" class="nav-link" data-scroll-target="#financing-round-nomenclature"><span class="header-section-number">15.2.3</span> <strong>Financing Round Nomenclature</strong></a></li>
  <li><a href="#the-angel-investor" id="toc-the-angel-investor" class="nav-link" data-scroll-target="#the-angel-investor"><span class="header-section-number">15.2.4</span> <strong>The Angel Investor</strong></a></li>
  <li><a href="#the-syndicate" id="toc-the-syndicate" class="nav-link" data-scroll-target="#the-syndicate"><span class="header-section-number">15.2.5</span> <strong>The Syndicate</strong></a></li>
  <li><a href="#the-lawyer" id="toc-the-lawyer" class="nav-link" data-scroll-target="#the-lawyer"><span class="header-section-number">15.2.6</span> <strong>The Lawyer</strong></a></li>
  <li><a href="#other-key-players" id="toc-other-key-players" class="nav-link" data-scroll-target="#other-key-players"><span class="header-section-number">15.2.7</span> <strong>Other Key Players</strong></a></li>
  </ul></li>
  <li><a href="#preparing-for-fundraising" id="toc-preparing-for-fundraising" class="nav-link" data-scroll-target="#preparing-for-fundraising"><span class="header-section-number">15.3</span> <strong>Preparing for Fundraising</strong></a>
  <ul class="collapse">
  <li><a href="#choosing-the-right-lawyer" id="toc-choosing-the-right-lawyer" class="nav-link" data-scroll-target="#choosing-the-right-lawyer"><span class="header-section-number">15.3.1</span> <strong>Choosing the Right Lawyer</strong></a></li>
  <li><a href="#proactive-versus-reactive-due-diligence-preparation" id="toc-proactive-versus-reactive-due-diligence-preparation" class="nav-link" data-scroll-target="#proactive-versus-reactive-due-diligence-preparation"><span class="header-section-number">15.3.2</span> <strong>Proactive versus Reactive (Due Diligence Preparation)</strong></a></li>
  <li><a href="#intellectual-property-ip" id="toc-intellectual-property-ip" class="nav-link" data-scroll-target="#intellectual-property-ip"><span class="header-section-number">15.3.3</span> <strong>Intellectual Property (IP)</strong></a></li>
  </ul></li>
  <li><a href="#how-to-raise-money" id="toc-how-to-raise-money" class="nav-link" data-scroll-target="#how-to-raise-money"><span class="header-section-number">15.4</span> <strong>How to Raise Money</strong></a>
  <ul class="collapse">
  <li><a href="#mindset-and-strategy" id="toc-mindset-and-strategy" class="nav-link" data-scroll-target="#mindset-and-strategy"><span class="header-section-number">15.4.1</span> <strong>Mindset and Strategy</strong></a></li>
  <li><a href="#fundraising-materials" id="toc-fundraising-materials" class="nav-link" data-scroll-target="#fundraising-materials"><span class="header-section-number">15.4.2</span> <strong>Fundraising Materials</strong></a></li>
  <li><a href="#finding-and-engaging-vcs" id="toc-finding-and-engaging-vcs" class="nav-link" data-scroll-target="#finding-and-engaging-vcs"><span class="header-section-number">15.4.3</span> <strong>Finding and Engaging VCs</strong></a></li>
  </ul></li>
  <li><a href="#overview-of-the-term-sheet" id="toc-overview-of-the-term-sheet" class="nav-link" data-scroll-target="#overview-of-the-term-sheet"><span class="header-section-number">15.5</span> <strong>Overview of the Term Sheet</strong></a>
  <ul class="collapse">
  <li><a href="#key-concepts-economics-and-control" id="toc-key-concepts-economics-and-control" class="nav-link" data-scroll-target="#key-concepts-economics-and-control"><span class="header-section-number">15.5.1</span> <strong>Key Concepts: Economics and Control</strong></a></li>
  </ul></li>
  <li><a href="#economic-terms-of-the-term-sheet" id="toc-economic-terms-of-the-term-sheet" class="nav-link" data-scroll-target="#economic-terms-of-the-term-sheet"><span class="header-section-number">15.6</span> <strong>Economic Terms of the Term Sheet</strong></a>
  <ul class="collapse">
  <li><a href="#valuation-and-price" id="toc-valuation-and-price" class="nav-link" data-scroll-target="#valuation-and-price"><span class="header-section-number">15.6.1</span> <strong>1. Valuation and Price</strong></a></li>
  <li><a href="#employee-option-pool" id="toc-employee-option-pool" class="nav-link" data-scroll-target="#employee-option-pool"><span class="header-section-number">15.6.2</span> <strong>2. Employee Option Pool</strong></a></li>
  <li><a href="#liquidation-preference" id="toc-liquidation-preference" class="nav-link" data-scroll-target="#liquidation-preference"><span class="header-section-number">15.6.3</span> <strong>3. Liquidation Preference</strong></a></li>
  <li><a href="#pay-to-play" id="toc-pay-to-play" class="nav-link" data-scroll-target="#pay-to-play"><span class="header-section-number">15.6.4</span> <strong>4. Pay-to-Play</strong></a></li>
  <li><a href="#vesting" id="toc-vesting" class="nav-link" data-scroll-target="#vesting"><span class="header-section-number">15.6.5</span> <strong>5. Vesting</strong></a></li>
  <li><a href="#exercise-period" id="toc-exercise-period" class="nav-link" data-scroll-target="#exercise-period"><span class="header-section-number">15.6.6</span> <strong>6. Exercise Period</strong></a></li>
  <li><a href="#antidilution" id="toc-antidilution" class="nav-link" data-scroll-target="#antidilution"><span class="header-section-number">15.6.7</span> <strong>7. Antidilution</strong></a></li>
  </ul></li>
  <li><a href="#control-terms-of-the-term-sheet" id="toc-control-terms-of-the-term-sheet" class="nav-link" data-scroll-target="#control-terms-of-the-term-sheet"><span class="header-section-number">15.7</span> <strong>Control Terms of the Term Sheet</strong></a>
  <ul class="collapse">
  <li><a href="#board-of-directors" id="toc-board-of-directors" class="nav-link" data-scroll-target="#board-of-directors"><span class="header-section-number">15.7.1</span> <strong>1. Board of Directors</strong></a></li>
  <li><a href="#protective-provisions" id="toc-protective-provisions" class="nav-link" data-scroll-target="#protective-provisions"><span class="header-section-number">15.7.2</span> <strong>2. Protective Provisions</strong></a></li>
  <li><a href="#drag-along-agreement" id="toc-drag-along-agreement" class="nav-link" data-scroll-target="#drag-along-agreement"><span class="header-section-number">15.7.3</span> <strong>3. Drag-Along Agreement</strong></a></li>
  <li><a href="#conversion" id="toc-conversion" class="nav-link" data-scroll-target="#conversion"><span class="header-section-number">15.7.4</span> <strong>4. Conversion</strong></a></li>
  </ul></li>
  <li><a href="#other-terms-of-the-term-sheet" id="toc-other-terms-of-the-term-sheet" class="nav-link" data-scroll-target="#other-terms-of-the-term-sheet"><span class="header-section-number">15.8</span> <strong>Other Terms of the Term Sheet</strong></a></li>
  <li><a href="#convertible-debt" id="toc-convertible-debt" class="nav-link" data-scroll-target="#convertible-debt"><span class="header-section-number">15.9</span> <strong>Convertible Debt</strong></a>
  <ul class="collapse">
  <li><a href="#pros-and-cons" id="toc-pros-and-cons" class="nav-link" data-scroll-target="#pros-and-cons"><span class="header-section-number">15.9.1</span> <strong>Pros and Cons</strong></a></li>
  <li><a href="#key-convertible-debt-terms" id="toc-key-convertible-debt-terms" class="nav-link" data-scroll-target="#key-convertible-debt-terms"><span class="header-section-number">15.9.2</span> <strong>Key Convertible Debt Terms</strong></a></li>
  <li><a href="#alternative-approaches" id="toc-alternative-approaches" class="nav-link" data-scroll-target="#alternative-approaches"><span class="header-section-number">15.9.3</span> <strong>Alternative Approaches</strong></a></li>
  </ul></li>
  <li><a href="#the-capitalization-table" id="toc-the-capitalization-table" class="nav-link" data-scroll-target="#the-capitalization-table"><span class="header-section-number">15.10</span> <strong>The Capitalization Table</strong></a>
  <ul class="collapse">
  <li><a href="#cap-table-calculation-example" id="toc-cap-table-calculation-example" class="nav-link" data-scroll-target="#cap-table-calculation-example"><span class="header-section-number">15.10.1</span> <strong>Cap Table Calculation Example</strong></a></li>
  <li><a href="#price-per-share-with-convertible-notes" id="toc-price-per-share-with-convertible-notes" class="nav-link" data-scroll-target="#price-per-share-with-convertible-notes"><span class="header-section-number">15.10.2</span> <strong>Price per Share with Convertible Notes</strong></a></li>
  </ul></li>
  <li><a href="#crowdfunding" id="toc-crowdfunding" class="nav-link" data-scroll-target="#crowdfunding"><span class="header-section-number">15.11</span> <strong>Crowdfunding</strong></a>
  <ul class="collapse">
  <li><a href="#product-crowdfunding" id="toc-product-crowdfunding" class="nav-link" data-scroll-target="#product-crowdfunding"><span class="header-section-number">15.11.1</span> <strong>1. Product Crowdfunding</strong></a></li>
  <li><a href="#equity-crowdfunding" id="toc-equity-crowdfunding" class="nav-link" data-scroll-target="#equity-crowdfunding"><span class="header-section-number">15.11.2</span> <strong>2. Equity Crowdfunding</strong></a></li>
  <li><a href="#token-crowdfunding-icos" id="toc-token-crowdfunding-icos" class="nav-link" data-scroll-target="#token-crowdfunding-icos"><span class="header-section-number">15.11.3</span> <strong>3. Token Crowdfunding (ICOs)</strong></a></li>
  </ul></li>
  <li><a href="#venture-debt" id="toc-venture-debt" class="nav-link" data-scroll-target="#venture-debt"><span class="header-section-number">15.12</span> <strong>Venture Debt</strong></a>
  <ul class="collapse">
  <li><a href="#the-role-and-players" id="toc-the-role-and-players" class="nav-link" data-scroll-target="#the-role-and-players"><span class="header-section-number">15.12.1</span> <strong>The Role and Players</strong></a></li>
  <li><a href="#how-lenders-think-psor" id="toc-how-lenders-think-psor" class="nav-link" data-scroll-target="#how-lenders-think-psor"><span class="header-section-number">15.12.2</span> <strong>How Lenders Think (PSOR)</strong></a></li>
  <li><a href="#key-terms" id="toc-key-terms" class="nav-link" data-scroll-target="#key-terms"><span class="header-section-number">15.12.3</span> <strong>Key Terms</strong></a></li>
  </ul></li>
  <li><a href="#how-venture-capital-funds-work" id="toc-how-venture-capital-funds-work" class="nav-link" data-scroll-target="#how-venture-capital-funds-work"><span class="header-section-number">15.13</span> <strong>How Venture Capital Funds Work</strong></a>
  <ul class="collapse">
  <li><a href="#fund-structure-and-compensation" id="toc-fund-structure-and-compensation" class="nav-link" data-scroll-target="#fund-structure-and-compensation"><span class="header-section-number">15.13.1</span> <strong>Fund Structure and Compensation</strong></a></li>
  <li><a href="#reserves-time-and-fiduciary-duties" id="toc-reserves-time-and-fiduciary-duties" class="nav-link" data-scroll-target="#reserves-time-and-fiduciary-duties"><span class="header-section-number">15.13.2</span> <strong>Reserves, Time, and Fiduciary Duties</strong></a></li>
  </ul></li>
  <li><a href="#negotiation-tactics" id="toc-negotiation-tactics" class="nav-link" data-scroll-target="#negotiation-tactics"><span class="header-section-number">15.14</span> <strong>Negotiation Tactics</strong></a>
  <ul class="collapse">
  <li><a href="#core-negotiation-principles" id="toc-core-negotiation-principles" class="nav-link" data-scroll-target="#core-negotiation-principles"><span class="header-section-number">15.14.1</span> <strong>Core Negotiation Principles</strong></a></li>
  </ul></li>
  <li><a href="#raising-money-the-right-way" id="toc-raising-money-the-right-way" class="nav-link" data-scroll-target="#raising-money-the-right-way"><span class="header-section-number">15.15</span> <strong>Raising Money the Right Way</strong></a></li>
  <li><a href="#issues-at-different-financing-stages" id="toc-issues-at-different-financing-stages" class="nav-link" data-scroll-target="#issues-at-different-financing-stages"><span class="header-section-number">15.16</span> <strong>Issues at Different Financing Stages</strong></a></li>
  <li><a href="#letters-of-intent-the-other-term-sheet" id="toc-letters-of-intent-the-other-term-sheet" class="nav-link" data-scroll-target="#letters-of-intent-the-other-term-sheet"><span class="header-section-number">15.17</span> <strong>Letters of Intent: The Other Term Sheet</strong></a>
  <ul class="collapse">
  <li><a href="#deal-structure-and-price" id="toc-deal-structure-and-price" class="nav-link" data-scroll-target="#deal-structure-and-price"><span class="header-section-number">15.17.1</span> <strong>Deal Structure and Price</strong></a></li>
  <li><a href="#asset-deal-vs.-stock-deal" id="toc-asset-deal-vs.-stock-deal" class="nav-link" data-scroll-target="#asset-deal-vs.-stock-deal"><span class="header-section-number">15.17.2</span> <strong>Asset Deal vs.&nbsp;Stock Deal</strong></a></li>
  <li><a href="#key-loi-clauses" id="toc-key-loi-clauses" class="nav-link" data-scroll-target="#key-loi-clauses"><span class="header-section-number">15.17.3</span> <strong>Key LOI Clauses</strong></a></li>
  </ul></li>
  <li><a href="#how-to-engage-an-investment-banker" id="toc-how-to-engage-an-investment-banker" class="nav-link" data-scroll-target="#how-to-engage-an-investment-banker"><span class="header-section-number">15.18</span> <strong>How to Engage an Investment Banker</strong></a>
  <ul class="collapse">
  <li><a href="#why-hire-a-banker" id="toc-why-hire-a-banker" class="nav-link" data-scroll-target="#why-hire-a-banker"><span class="header-section-number">15.18.1</span> <strong>Why Hire a Banker?</strong></a></li>
  <li><a href="#negotiating-the-engagement-letter" id="toc-negotiating-the-engagement-letter" class="nav-link" data-scroll-target="#negotiating-the-engagement-letter"><span class="header-section-number">15.18.2</span> <strong>Negotiating the Engagement Letter</strong></a></li>
  </ul></li>
  <li><a href="#why-do-term-sheets-even-exist" id="toc-why-do-term-sheets-even-exist" class="nav-link" data-scroll-target="#why-do-term-sheets-even-exist"><span class="header-section-number">15.19</span> <strong>Why Do Term Sheets Even Exist?</strong></a>
  <ul class="collapse">
  <li><a href="#constraining-behavior-and-aligning-incentives" id="toc-constraining-behavior-and-aligning-incentives" class="nav-link" data-scroll-target="#constraining-behavior-and-aligning-incentives"><span class="header-section-number">15.19.1</span> <strong>1. Constraining Behavior and Aligning Incentives</strong></a></li>
  <li><a href="#transaction-costs" id="toc-transaction-costs" class="nav-link" data-scroll-target="#transaction-costs"><span class="header-section-number">15.19.2</span> <strong>2. Transaction Costs</strong></a></li>
  <li><a href="#agency-costs-and-information-asymmetry" id="toc-agency-costs-and-information-asymmetry" class="nav-link" data-scroll-target="#agency-costs-and-information-asymmetry"><span class="header-section-number">15.19.3</span> <strong>3. Agency Costs and Information Asymmetry</strong></a></li>
  <li><a href="#reputation-constraints" id="toc-reputation-constraints" class="nav-link" data-scroll-target="#reputation-constraints"><span class="header-section-number">15.19.4</span> <strong>4. Reputation Constraints</strong></a></li>
  </ul></li>
  <li><a href="#legal-things-every-entrepreneur-should-know" id="toc-legal-things-every-entrepreneur-should-know" class="nav-link" data-scroll-target="#legal-things-every-entrepreneur-should-know"><span class="header-section-number">15.20</span> <strong>Legal Things Every Entrepreneur Should Know</strong></a>
  <ul class="collapse">
  <li><a href="#intellectual-property-ip-1" id="toc-intellectual-property-ip-1" class="nav-link" data-scroll-target="#intellectual-property-ip-1"><span class="header-section-number">15.20.1</span> <strong>Intellectual Property (IP)</strong></a></li>
  <li><a href="#corporate-and-employment-structure" id="toc-corporate-and-employment-structure" class="nav-link" data-scroll-target="#corporate-and-employment-structure"><span class="header-section-number">15.20.2</span> <strong>Corporate and Employment Structure</strong></a></li>
  <li><a href="#stock-and-tax-issues" id="toc-stock-and-tax-issues" class="nav-link" data-scroll-target="#stock-and-tax-issues"><span class="header-section-number">15.20.3</span> <strong>Stock and Tax Issues</strong></a></li>
  </ul></li>
  <li><a href="#final-comprehensive-summary" id="toc-final-comprehensive-summary" class="nav-link" data-scroll-target="#final-comprehensive-summary"><span class="header-section-number">15.21</span> <strong>Final Comprehensive Summary</strong></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Venture Deals</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="executive-summary-critical-takeaways" class="level2" data-number="15.1">
<h2 data-number="15.1" class="anchored" data-anchor-id="executive-summary-critical-takeaways"><span class="header-section-number">15.1</span> <strong>Executive Summary: Critical Takeaways</strong></h2>
<p><em>Venture Deals</em> demystifies the process of venture capital financing, arguing that the term sheet negotiation is the most critical juncture in forming a long-term partnership between entrepreneurs and investors.</p>
<ol type="1">
<li><strong>Focus on the Core:</strong> Virtually all venture negotiations boil down to two essential concepts: <strong>Economics</strong> (who gets what return in a liquidity event) and <strong>Control</strong> (who makes which decisions). An entrepreneur should focus negotiation energy primarily on <strong>Valuation, Liquidation Preference, Employee Option Pool, Board Composition, Protective Provisions, and Drag-Along Agreements</strong>.<br>
</li>
<li><strong>Preparation and Process:</strong> Successful fundraising requires meticulous preparation, including organizing all legal and financial documentation (due diligence materials) and structuring the company as a <strong>Delaware C Corporation</strong>. Entrepreneurs must adopt a “Do. Or Do Not. There Is No Try.” mindset.<br>
</li>
<li><strong>Leverage is Key:</strong> The most effective way to achieve favorable terms is to create competition by generating multiple interested VCs (leverage). Never reveal the names of competing firms to preserve this leverage.<br>
</li>
<li><strong>Understand Your Partner:</strong> Entrepreneurs must conduct due diligence on VCs, understanding the VC firm’s hierarchy, fund structure, management fees, and <strong>Carried Interest</strong> (profit share) to grasp their motivations and potential conflicts of interest (fiduciary duties).<br>
</li>
<li><strong>Alternative Financing:</strong> Convertible debt (and its derivatives like the SAFE/KISS) serves as a popular seed-stage alternative to traditional equity, primarily by deferring the challenging valuation discussion through the use of a <strong>Discount</strong> and/or a <strong>Valuation Cap</strong>.<br>
</li>
<li><strong>Legal Expertise:</strong> Hire a competent, experienced lawyer who understands venture deals and whose negotiating style reflects positively on the entrepreneur.</li>
</ol>
</section>
<section id="the-players" class="level2" data-number="15.2">
<h2 data-number="15.2" class="anchored" data-anchor-id="the-players"><span class="header-section-number">15.2</span> <strong>The Players</strong></h2>
<p>The financing process involves more than just the entrepreneur and the venture capitalist; it includes a variety of specialized participants whose experience, motivation, and power dynamics must be understood.</p>
<section id="the-entrepreneur-founder" class="level3" data-number="15.2.1">
<h3 data-number="15.2.1" class="anchored" data-anchor-id="the-entrepreneur-founder"><span class="header-section-number">15.2.1</span> <strong>The Entrepreneur (Founder)</strong></h3>
<p>The entrepreneur is the core of the entrepreneurial universe; without them, the ecosystem would not exist. Founders must remain deeply involved in the financing process and should never outsource core decisions to their lawyers. Investors often utilize mechanisms like <strong>vesting</strong> and <strong>drag-along rights</strong> not only for their own protection but also sometimes to protect cofounders from each other, ensuring clean resolutions upon a founder’s departure.</p>
</section>
<section id="the-venture-capitalist-vc" class="level3" data-number="15.2.2">
<h3 data-number="15.2.2" class="anchored" data-anchor-id="the-venture-capitalist-vc"><span class="header-section-number">15.2.2</span> <strong>The Venture Capitalist (VC)</strong></h3>
<p>VCs vary widely in shape, size, and experience. Understanding the hierarchy within a VC firm is critical for the entrepreneur to know who possesses actual decision-making authority:</p>
<ul>
<li><strong>Managing Director (MD) or General Partner (GP):</strong> The most senior partners who make final investment decisions and typically sit on boards.<br>
</li>
<li><strong>Partners:</strong> Titles can be misleading. Often, they are junior professionals (principals or directors) or involved in specific activities (recruiting, operations) but lack decision-making power.<br>
</li>
<li><strong>Principals/Directors:</strong> Junior deal professionals who usually need support from an MD/GP to push a deal forward.<br>
</li>
<li><strong>Associates:</strong> Work for deal partners, scouting deals, assisting with due diligence, and managing the <strong>capitalization table (cap table)</strong>.<br>
</li>
<li><strong>Analysts:</strong> Very junior employees focused on crunching numbers and writing memos.<br>
</li>
<li><strong>Venture Partners/Operating Partners (VPs/OPs):</strong> Experienced entrepreneurs with part-time relationships; they advocate for deals but generally need MD support.<br>
</li>
<li><strong>Entrepreneurs in Residence (EIRs):</strong> Experienced founders temporarily housed at a VC firm, helping with diligence while developing their next idea.</li>
</ul>
<p><strong>Application:</strong> Entrepreneurs should insist on developing a direct relationship with an MD or GP, as they hold the decision-making authority (“mojo”) within the firm.</p>
</section>
<section id="financing-round-nomenclature" class="level3" data-number="15.2.3">
<h3 data-number="15.2.3" class="anchored" data-anchor-id="financing-round-nomenclature"><span class="header-section-number">15.2.3</span> <strong>Financing Round Nomenclature</strong></h3>
<p>VC firms generally define themselves by the stage of financing they target:</p>
<ul>
<li><strong>Micro VC Funds:</strong> Small firms, often run by a single GP, typically investing less than $15 million total, exclusively at the seed and early stage.<br>
</li>
<li><strong>Seed Stage Funds:</strong> Larger than Micro VCs (up to $150 million), focusing on being the first institutional money and providing the first non-company board member.<br>
</li>
<li><strong>Early Stage Funds:</strong> $100 million to $300 million in size, investing in seed and Series A deals, sometimes leading Series B.<br>
</li>
<li><strong>Mid Stage Funds (Growth Investors):</strong> Larger funds ($200 million to $1 billion+) investing in Series B and later rounds, when a company needs capital to accelerate proven growth.<br>
</li>
<li><strong>Pre-Seed, Series Seed, Series A, B, etc.:</strong> Sequential financing rounds designated by letters.</li>
</ul>
</section>
<section id="the-angel-investor" class="level3" data-number="15.2.4">
<h3 data-number="15.2.4" class="anchored" data-anchor-id="the-angel-investor"><span class="header-section-number">15.2.4</span> <strong>The Angel Investor</strong></h3>
<p>Angels are individuals who invest their own money, usually in early rounds, and may not participate in future rounds. <strong>Super angels</strong> are very active, often successful entrepreneurs who invest frequently and may eventually raise a fund, transitioning into a Micro VC.</p>
<p><strong>Application:</strong> If dealing with a diffuse group of angel investors (friends and family), consider setting up a single <strong>special-purpose limited partnership</strong> controlled by one person to simplify future processes that require shareholder signatures (e.g., subsequent financings or sale of the company).</p>
</section>
<section id="the-syndicate" class="level3" data-number="15.2.5">
<h3 data-number="15.2.5" class="anchored" data-anchor-id="the-syndicate"><span class="header-section-number">15.2.5</span> <strong>The Syndicate</strong></h3>
<p>A <strong>syndicate</strong> is a collection of investors who participate in a financing round. The <strong>lead investor</strong> negotiates the terms for the entire syndicate. Entrepreneurs must communicate with every investor, but they should insist that the lead investor speaks for the group on deal terms to avoid negotiating the deal multiple times.</p>
</section>
<section id="the-lawyer" class="level3" data-number="15.2.6">
<h3 data-number="15.2.6" class="anchored" data-anchor-id="the-lawyer"><span class="header-section-number">15.2.6</span> <strong>The Lawyer</strong></h3>
<p>A great, experienced lawyer is invaluable to an entrepreneur, helping negotiate and focus on the terms that truly matter (economics and control). An inexperienced lawyer can cause harm, fighting over irrelevant issues, increasing unnecessary tension, and running up bills. Early-stage financings should typically cost between $5,000 and $20,000, and typical financings between $20,000 and $40,000.</p>
</section>
<section id="other-key-players" class="level3" data-number="15.2.7">
<h3 data-number="15.2.7" class="anchored" data-anchor-id="other-key-players"><span class="header-section-number">15.2.7</span> <strong>Other Key Players</strong></h3>
<ul>
<li><strong>The Accountant:</strong> Necessary for cross-border issues or when dealing with complex corporate restructuring.<br>
</li>
<li><strong>The Banker:</strong> Useful in later-stage deals or for deals involving financial sponsors (like private-equity firms).<br>
</li>
<li><strong>The Mentor:</strong> Experienced individuals who advise the company, ideally without mandatory fees or extensive option grants unless their performance as an ongoing adviser merits it.</li>
</ul>
</section>
</section>
<section id="preparing-for-fundraising" class="level2" data-number="15.3">
<h2 data-number="15.3" class="anchored" data-anchor-id="preparing-for-fundraising"><span class="header-section-number">15.3</span> <strong>Preparing for Fundraising</strong></h2>
<p>Preparation is key to avoiding major issues during fundraising.</p>
<section id="choosing-the-right-lawyer" class="level3" data-number="15.3.1">
<h3 data-number="15.3.1" class="anchored" data-anchor-id="choosing-the-right-lawyer"><span class="header-section-number">15.3.1</span> <strong>Choosing the Right Lawyer</strong></h3>
<p>The legal adviser guides the company through its entire corporate lifecycle. When selecting corporate counsel:</p>
<ul>
<li>Seek an attorney or firm with a proven track record representing startups.<br>
</li>
<li>Ensure a personal connection and complete trust, as intimate business details will be shared.<br>
</li>
<li>Prioritize a competent lawyer familiar with startups over one with a low hourly rate, as efficiency dictates the final bill.</li>
</ul>
</section>
<section id="proactive-versus-reactive-due-diligence-preparation" class="level3" data-number="15.3.2">
<h3 data-number="15.3.2" class="anchored" data-anchor-id="proactive-versus-reactive-due-diligence-preparation"><span class="header-section-number">15.3.2</span> <strong>Proactive versus Reactive (Due Diligence Preparation)</strong></h3>
<p>A startup must be prepared to meet investors’ expectations prior to seeking funding:</p>
<ol type="1">
<li><strong>Corporate Structure:</strong> Ensure the company is structured as a <strong>C Corporation</strong> registered in Delaware.<br>
</li>
<li><strong>Data Site:</strong> Establish an organized data site (e.g., Dropbox/Google folder) containing all legal and financial records for easy investor review.
<ul>
<li>Documents include: Certificate of Incorporation, Bylaws, board minutes, shareholder actions, capital stock documents, financial records, and employment agreements.<br>
</li>
</ul></li>
<li><strong>Capitalization Table (Cap Table):</strong> Corporate counsel assists in preparation, but founders must be well versed in the details of this spreadsheet listing all securities and ownership.<br>
</li>
<li><strong>Document Execution:</strong> Review all documents to ensure proper execution (e.g., signatures) before negotiations begin.</li>
</ol>
</section>
<section id="intellectual-property-ip" class="level3" data-number="15.3.3">
<h3 data-number="15.3.3" class="anchored" data-anchor-id="intellectual-property-ip"><span class="header-section-number">15.3.3</span> <strong>Intellectual Property (IP)</strong></h3>
<p>IP encompasses patents, <strong>copyrights</strong> (code), <strong>trademarks</strong> (brand), and <strong>trade secrets</strong>. Investors require a clear, documented chain of title for all IP:</p>
<ul>
<li><strong>Agreements:</strong> Anyone who has touched the company’s IP must sign <strong>Proprietary Information and Inventions Agreements</strong> (PIIAs) containing confidentiality and IP assignment provisions. Failure to secure a single IP assignment can cause a deal to fail.<br>
</li>
<li><strong>Founder IP:</strong> Founders must make a clean break from former employers, as previous employment contracts often claim IP created while employed, even if created on personal time.<br>
</li>
<li><strong>Service Providers:</strong> Contractors and external advisers must also sign agreements ensuring that all IP created is assigned exclusively to the company.</li>
</ul>
</section>
</section>
<section id="how-to-raise-money" class="level2" data-number="15.4">
<h2 data-number="15.4" class="anchored" data-anchor-id="how-to-raise-money"><span class="header-section-number">15.4</span> <strong>How to Raise Money</strong></h2>
<p>The primary goal of fundraising is to secure several <strong>term sheets</strong> to generate competition and leverage better terms.</p>
<section id="mindset-and-strategy" class="level3" data-number="15.4.1">
<h3 data-number="15.4.1" class="anchored" data-anchor-id="mindset-and-strategy"><span class="header-section-number">15.4.1</span> <strong>Mindset and Strategy</strong></h3>
<ul>
<li><strong>Commitment:</strong> Approach fundraising with the conviction of success: “Do. Or Do Not. There Is No Try.”.<br>
</li>
<li><strong>Determine Amount:</strong> Calculate the capital needed to fund operations until the next meaningful milestone (e.g., 12 months for a seed-stage software company). State a <strong>specific number</strong> (not a range) to avoid appearing uncertain.</li>
</ul>
</section>
<section id="fundraising-materials" class="level3" data-number="15.4.2">
<h3 data-number="15.4.2" class="anchored" data-anchor-id="fundraising-materials"><span class="header-section-number">15.4.2</span> <strong>Fundraising Materials</strong></h3>
<p>Essential materials must be clear, concise, substantive, and able to stand on their own without the entrepreneur needing to explain them.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Material</th>
<th>Description and Purpose</th>
<th>Application Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Short Description/Elevator Pitch</strong></td>
<td>1–3 paragraphs summarizing product, team, and business; often the main text of an introductory email.</td>
<td>Must be direct and include a clear request for the next step.</td>
</tr>
<tr class="even">
<td><strong>Executive Summary</strong></td>
<td>Short, well-written overview (up to 3 pages) detailing the problem, product, team, and high-level financials.</td>
<td>Demonstrates critical thinking and communication skills.</td>
</tr>
<tr class="odd">
<td><strong>Presentation (PowerPoint)</strong></td>
<td>10–20 visual slides reinforcing the executive summary. Tune the content to the audience.</td>
<td>Focus on flow and professional design (form matters). Core slides: problem, opportunity size, team strength, competition, plan, financials.</td>
</tr>
<tr class="even">
<td><strong>Financial Model</strong></td>
<td>Focus on expense side and <strong>burn rate</strong>; revenue projections are 100% likely to be wrong.</td>
<td>Used by VCs to evaluate how the entrepreneur thinks about the business dynamics.</td>
</tr>
<tr class="odd">
<td><strong>Demo/Prototype (Alpha)</strong></td>
<td>Allows VCs to interact directly with the vision; far more important than a business plan for early-stage firms.</td>
<td>Gives VCs insight into the team’s ability to build and execute.</td>
</tr>
<tr class="even">
<td><strong>Private Placement Memorandum (PPM)</strong></td>
<td>Traditional business plan wrapped in legal disclaimers. Rarely used or desired by VCs in early-stage deals.</td>
<td>Waste of time and money in early stages.</td>
</tr>
</tbody>
</table>
</section>
<section id="finding-and-engaging-vcs" class="level3" data-number="15.4.3">
<h3 data-number="15.4.3" class="anchored" data-anchor-id="finding-and-engaging-vcs"><span class="header-section-number">15.4.3</span> <strong>Finding and Engaging VCs</strong></h3>
<ol type="1">
<li><strong>Research:</strong> Use referrals and social media/websites to understand what types of companies, stages, and sectors a VC firm invests in.<br>
</li>
<li><strong>Referrals:</strong> The majority of successful inquiries come through referrals.<br>
</li>
<li><strong>Relationships:</strong> View fundraising as an evolving relationship, not a single transaction. Seek advice before asking for money.<br>
</li>
<li><strong>Due Diligence:</strong> Once engaged, VCs start internal due diligence. If the VC makes you perform excessive busywork (e.g., requiring 5-year projections for a pre-revenue company), it may signal they are not deeply interested or are using junior staff for a “fishing expedition”.<br>
</li>
<li><strong>Feedback:</strong> If a VC passes, politely but persistently insist on receiving feedback for learning purposes.<br>
</li>
<li><strong>Closing:</strong> Ensure a lead VC is found who can write a check large enough to drive the financing. Once the nonbinding term sheet is signed, the final step is executing the <strong>definitive agreements</strong> and receiving the cash.</li>
</ol>
</section>
</section>
<section id="overview-of-the-term-sheet" class="level2" data-number="15.5">
<h2 data-number="15.5" class="anchored" data-anchor-id="overview-of-the-term-sheet"><span class="header-section-number">15.5</span> <strong>Overview of the Term Sheet</strong></h2>
<p>The term sheet is the summary document outlining the key provisions of a venture financing, acting as the blueprint for the legal agreements.</p>
<section id="key-concepts-economics-and-control" class="level3" data-number="15.5.1">
<h3 data-number="15.5.1" class="anchored" data-anchor-id="key-concepts-economics-and-control"><span class="header-section-number">15.5.1</span> <strong>Key Concepts: Economics and Control</strong></h3>
<p>The entire term sheet negotiation focuses on these two primary concepts:</p>
<ul>
<li><strong>Economics:</strong> Terms that directly impact the investors’ return in a <strong>liquidity event</strong> (e.g., sale, IPO, wind down).<br>
</li>
<li><strong>Control:</strong> Mechanisms allowing investors to affirmatively exercise control (e.g., board seats) or veto corporate decisions (e.g., protective provisions).</li>
</ul>
<p>VCs typically purchase <strong>Preferred Stock</strong>, which carries preferential terms and rights compared to the <strong>Common Stock</strong>held by founders and employees.</p>
</section>
</section>
<section id="economic-terms-of-the-term-sheet" class="level2" data-number="15.6">
<h2 data-number="15.6" class="anchored" data-anchor-id="economic-terms-of-the-term-sheet"><span class="header-section-number">15.6</span> <strong>Economic Terms of the Term Sheet</strong></h2>
<section id="valuation-and-price" class="level3" data-number="15.6.1">
<h3 data-number="15.6.1" class="anchored" data-anchor-id="valuation-and-price"><span class="header-section-number">15.6.1</span> <strong>1. Valuation and Price</strong></h3>
<p><strong>Valuation</strong> determines the price per share and thus the percentage of the company being sold.</p>
<ul>
<li><strong>Pre-Money Valuation:</strong> The agreed value of the company <em>before</em> the new investment.<br>
</li>
<li><strong>Post-Money Valuation:</strong> Pre-money valuation plus the amount of the investment.</li>
</ul>
<p>Entrepreneurs must clarify whether a VC’s valuation quote is pre-money or post-money, as this dramatically impacts dilution. The <strong>price per share</strong> is calculated by dividing the pre-money valuation by the fully diluted capitalization. <strong>Fully diluted</strong> includes all outstanding stock, plus all rights to acquire stock in the future, crucially including the <strong>employee option pool</strong>.</p>
<p><strong>Factors Influencing Valuation:</strong></p>
<ul>
<li><strong>Stage of the Company:</strong> Early-stage depends heavily on team experience and opportunity perception; later-stage depends on historical financial performance.<br>
</li>
<li><strong>Competition:</strong> Multiple VCs interested in a deal increases price.<br>
</li>
<li><strong>Market Size/Trendiness:</strong> Larger or trendier markets can influence higher pricing.<br>
</li>
<li><strong>Financial Numbers:</strong> Past performance, revenue predictions, cash burn, and headcount all factor in, especially in later stages.</li>
</ul>
</section>
<section id="employee-option-pool" class="level3" data-number="15.6.2">
<h3 data-number="15.6.2" class="anchored" data-anchor-id="employee-option-pool"><span class="header-section-number">15.6.2</span> <strong>2. Employee Option Pool</strong></h3>
<p>The <strong>employee option pool</strong> is stock reserved for issuance to directors, officers, employees, and consultants. This pool is typically “refreshed” or created <em>prior</em> to the financing, meaning founders suffer dilution from the pool, but the VC does not buy into the pool. The size of the pool (often 10%–20% of post-money cap) should be negotiated concurrently with valuation.</p>
</section>
<section id="liquidation-preference" class="level3" data-number="15.6.3">
<h3 data-number="15.6.3" class="anchored" data-anchor-id="liquidation-preference"><span class="header-section-number">15.6.3</span> <strong>3. Liquidation Preference</strong></h3>
<p>The liquidation preference dictates the distribution of proceeds when a company undergoes a <strong>liquidation event</strong> (usually a sale, merger, or wind down). It comprises two components: the preference multiple and participation rights.</p>
<p><strong>A. Preference Multiple:</strong></p>
<ul>
<li><strong>1× (Standard):</strong> Investors get 100% of their money back before common stock receives anything.<br>
</li>
<li><strong>Higher Multiples (e.g., 2×):</strong> Common in distressed or late-stage financings; ensures investors receive a multiple of their cash back.</li>
</ul>
<p><strong>B. Participation Rights:</strong> Dictate whether the investor shares in the remaining proceeds <em>after</em> receiving the initial preference.</p>
<ol type="1">
<li><strong>No Participation (Nonparticipating Preferred/Simple Preferred):</strong> Investor chooses the greater payout: (1) taking the liquidation preference and nothing else, OR (2) converting shares to common stock and participating pro rata in all proceeds.<br>
</li>
<li><strong>Full Participation:</strong> Investor receives the liquidation preference PLUS converts their shares to common-equivalent and participates pro rata in all remaining proceeds. This is the “have your cake and eat it too” scenario.<br>
</li>
<li><strong>Capped Participation:</strong> Investor receives preference PLUS participation until a pre-defined multiple (<strong>cap</strong>) of the original purchase price (e.g., 3×) is reached. Once the cap is hit, participation stops.</li>
</ol>
<p><strong>Multiple Series Preferences:</strong> When different series of preferred stock exist, preferences may be <strong>stacked</strong> (later series gets preference first) or <strong>pari passu (blended preferences)</strong> (all series share pro rata). The <strong>liquidation preference overhang</strong> is the total money that must be returned to satisfy all preferences before common holders receive proceeds.</p>
</section>
<section id="pay-to-play" class="level3" data-number="15.6.4">
<h3 data-number="15.6.4" class="anchored" data-anchor-id="pay-to-play"><span class="header-section-number">15.6.4</span> <strong>4. Pay-to-Play</strong></h3>
<p>This provision is a control mechanism designed to align investor interests. If preferred stockholders (usually Major Investors) fail to participate pro rata in a future financing (typically a <strong>Qualified Financing</strong>—often a down round), their preferred stock is automatically converted into common stock, stripping them of their preferential rights (liquidation preference, veto rights, etc.).</p>
</section>
<section id="vesting" class="level3" data-number="15.6.5">
<h3 data-number="15.6.5" class="anchored" data-anchor-id="vesting"><span class="header-section-number">15.6.5</span> <strong>5. Vesting</strong></h3>
<p><strong>Vesting</strong> dictates when an employee or founder earns the ownership rights to their stock or options.</p>
<ul>
<li><strong>Standard Schedule:</strong> Typically 4 years with a <strong>one-year cliff</strong> (meaning no stock vests until the individual completes one year of service).<br>
</li>
<li><strong>Founders’ Stock:</strong> VCs often impose vesting terms on founders’ stock to ensure their retention and commitment to the business.<br>
</li>
<li><strong>Acceleration on Change of Control (Acquisition):</strong>
<ul>
<li><strong>Single-Trigger Acceleration:</strong> Vests all remaining unvested shares automatically upon acquisition. VCs typically resist this as acquirers usually want forward-looking incentive.<br>
</li>
<li><strong>Double-Trigger Acceleration:</strong> Vests shares only if (1) an acquisition occurs, AND (2) the employee/founder is terminated without cause (or resigns with good reason) within a defined period (e.g., 1 year) following the acquisition. This is the most common clause in VC deals.</li>
</ul></li>
</ul>
</section>
<section id="exercise-period" class="level3" data-number="15.6.6">
<h3 data-number="15.6.6" class="anchored" data-anchor-id="exercise-period"><span class="header-section-number">15.6.6</span> <strong>6. Exercise Period</strong></h3>
<p>The amount of time an employee has to purchase their vested stock options after leaving the company (e.g., 90 days).</p>
</section>
<section id="antidilution" class="level3" data-number="15.6.7">
<h3 data-number="15.6.7" class="anchored" data-anchor-id="antidilution"><span class="header-section-number">15.6.7</span> <strong>7. Antidilution</strong></h3>
<p><strong>Antidilution</strong> provisions protect investors when a company issues equity in a <strong>down round</strong> (at a price lower than the investor originally paid). This changes the investor’s conversion ratio, increasing the number of common shares they receive upon conversion.</p>
<ul>
<li><strong>Full Ratchet:</strong> The harshest form. If one share is sold at a lower price, all previous investors’ shares are repriced down to that new, lower price.<br>
</li>
<li><strong>Weighted Average:</strong> The most common form. The adjustment considers the magnitude (number of shares issued) of the lower-priced round, resulting in a less severe dilution adjustment.
<ul>
<li><strong>Broad-Based:</strong> Includes all common stock outstanding, options, and warrants in the calculation (less harsh).<br>
</li>
<li><strong>Narrow-Based:</strong> Limits the calculation to only currently outstanding securities (harsher).<br>
</li>
</ul></li>
<li><strong>Carve-outs:</strong> Standard exceptions where antidilution does not apply, such as employee option grants, shares issued in M&amp;A, or shares issued for bank debt.</li>
</ul>
</section>
</section>
<section id="control-terms-of-the-term-sheet" class="level2" data-number="15.7">
<h2 data-number="15.7" class="anchored" data-anchor-id="control-terms-of-the-term-sheet"><span class="header-section-number">15.7</span> <strong>Control Terms of the Term Sheet</strong></h2>
<section id="board-of-directors" class="level3" data-number="15.7.1">
<h3 data-number="15.7.1" class="anchored" data-anchor-id="board-of-directors"><span class="header-section-number">15.7.1</span> <strong>1. Board of Directors</strong></h3>
<p>The board is the company’s most powerful element, approving budgets, mergers, financings, and having the power to hire and fire the CEO.</p>
<p><strong>Structure Breakdown:</strong></p>
<ul>
<li>Boards are typically 3 or 5 members for early-stage companies.<br>
</li>
<li>Seats are generally divided among <strong>Preferred Directors</strong> (elected by investors), <strong>Common Directors</strong> (elected by common holders, usually founders/CEO), and <strong>Outside Directors</strong> (mutually agreed upon or elected by both classes voting together).<br>
</li>
<li>An <strong>Outside Director</strong> brings impartiality and diverse thought.</li>
</ul>
</section>
<section id="protective-provisions" class="level3" data-number="15.7.2">
<h3 data-number="15.7.2" class="anchored" data-anchor-id="protective-provisions"><span class="header-section-number">15.7.2</span> <strong>2. Protective Provisions</strong></h3>
<p>These provisions grant veto rights to investors (usually a majority of the preferred stock) over certain actions, protecting their investment. Standard protective provisions typically cover actions such as:</p>
<ol type="1">
<li>Altering preferred stock rights.<br>
</li>
<li>Increasing/decreasing authorized shares.<br>
</li>
<li>Creating senior or parity classes of shares.<br>
</li>
<li>Redeeming/repurchasing common stock.<br>
</li>
<li>Mergers, reorganization, or sale of control.<br>
</li>
<li>Amending Certificate of Incorporation or Bylaws.<br>
</li>
<li>Increasing/decreasing the board size.<br>
</li>
<li>Paying or declaring dividends.<br>
</li>
<li>Incurring significant debt (often above a threshold like $100,000).</li>
</ol>
<p><strong>Application:</strong> Entrepreneurs should ensure that if multiple series of stock exist (Series A, B, etc.), the investors vote as a <strong>single class</strong> for protective provisions to prevent a small block of investors from holding up important decisions.</p>
</section>
<section id="drag-along-agreement" class="level3" data-number="15.7.3">
<h3 data-number="15.7.3" class="anchored" data-anchor-id="drag-along-agreement"><span class="header-section-number">15.7.3</span> <strong>3. Drag-Along Agreement</strong></h3>
<p>A <strong>drag-along agreement</strong> allows a majority of a specific class of shares (usually Preferred Stock, often a majority of the investors) to force all other shareholders (including founders and common holders) to consent to and participate in a sale or liquidation of the company. This prevents small minority shareholders from blocking an advantageous exit.</p>
</section>
<section id="conversion" class="level3" data-number="15.7.4">
<h3 data-number="15.7.4" class="anchored" data-anchor-id="conversion"><span class="header-section-number">15.7.4</span> <strong>4. Conversion</strong></h3>
<p>The right of preferred shareholders to convert their shares to common stock.</p>
<ul>
<li><strong>Automatic Conversion:</strong> Conversion is automatically triggered upon a <strong>Qualified IPO</strong> (QIPO). QIPO thresholds are negotiable, typically requiring a minimum price (e.g., 3× the original price) and a minimum offering size (e.g., $15 million). Conversion is often required by investment bankers for a clean offering structure.</li>
</ul>
</section>
</section>
<section id="other-terms-of-the-term-sheet" class="level2" data-number="15.8">
<h2 data-number="15.8" class="anchored" data-anchor-id="other-terms-of-the-term-sheet"><span class="header-section-number">15.8</span> <strong>Other Terms of the Term Sheet</strong></h2>
<p>These terms are generally less critical than economics and control, impacting the deal mainly in downside scenarios or involving standard rights.</p>
<ul>
<li><strong>Dividends:</strong> Rarely declared in early-stage VC deals. Can be <strong>cumulative</strong> (accrue yearly, usually 6%–10%) or <strong>noncumulative</strong> (only paid if the board declares them). Cumulative dividends only substantially impact returns in low-multiple exit scenarios.<br>
</li>
<li><strong>Redemption Rights:</strong> Give investors the right to force the company to repurchase their preferred stock, typically starting five years after the closing. The <strong>adverse change redemption</strong> is an overreaching clause giving investors the right to redeem upon arbitrary adverse judgment and should be avoided.<br>
</li>
<li><strong>Conditions Precedent to Financing:</strong> Lists prerequisites for funding. Important nonbinding items include: (1) <strong>Completion of satisfactory legal documentation and due diligence</strong>, (2) <strong>Satisfactory completion of due diligence</strong>, and (3) specific terms like <strong>Approval by investors’ partnerships</strong> (meaning the VC firm issuing the sheet hasn’t fully committed yet).<br>
</li>
<li><strong>Information Rights:</strong> Defines the minimum financial data the company must regularly provide to investors (e.g., annual budget, audited financial statements).<br>
</li>
<li><strong>Registration Rights:</strong> Rights detailing how investors can force or participate in the registration of their shares for public sale (usually in an IPO scenario). Generally complex but routine boilerplate.<br>
</li>
<li><strong>Right of First Refusal (ROFR):</strong> Also known as <strong>pro rata rights</strong>. Allows investors to purchase their proportionate share of any future equity issuance by the company, maintaining their ownership percentage. <strong>Super pro rata rights</strong>allow purchasing multiples of their proportional share and should be resisted.<br>
</li>
<li><strong>Voting Rights:</strong> Generally states that Preferred Stock votes alongside Common Stock on an as-converted basis, except where specified (protective provisions).<br>
</li>
<li><strong>Restriction on Sales (ROFR on Common):</strong> Gives the company (and often its investors) the right to refuse or exercise a right of first refusal on private transfers of common stock. This controls the private company’s shareholder base.<br>
</li>
<li><strong>Proprietary Information and Inventions Agreement (PIIA):</strong> A mandatory clause ensuring that all IP is owned by the company; must be signed by current and former officers/employees/consultants.<br>
</li>
<li><strong>Co-Sale Agreement:</strong> If founders sell shares (often in a secondary sale), investors have the right to participate in the sale on a proportional basis.<br>
</li>
<li><strong>Founders’ Activities:</strong> Clause requiring founders to devote 100% of their professional time to the company.<br>
</li>
<li><strong>No-Shop Agreement:</strong> A <strong>binding</strong> provision requiring the company to cease seeking other financing or acquisition proposals once the term sheet is signed.<br>
</li>
<li><strong>Indemnification:</strong> Requires the company to legally protect (indemnify) its board members and investors against certain liabilities.<br>
</li>
<li><strong>Assignment:</strong> Permits VCs to transfer shares to affiliated funds or partners.</li>
</ul>
</section>
<section id="convertible-debt" class="level2" data-number="15.9">
<h2 data-number="15.9" class="anchored" data-anchor-id="convertible-debt"><span class="header-section-number">15.9</span> <strong>Convertible Debt</strong></h2>
<p><strong>Convertible Debt</strong> is a loan that automatically converts into equity upon a future financing event, most often preferred stock.</p>
<section id="pros-and-cons" class="level3" data-number="15.9.1">
<h3 data-number="15.9.1" class="anchored" data-anchor-id="pros-and-cons"><span class="header-section-number">15.9.1</span> <strong>Pros and Cons</strong></h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Convertible Debt</th>
<th>Equity Financing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Pros:</strong> Easier, quicker, cheaper transaction; avoids setting a precise valuation, deferring negotiation.</td>
<td><strong>Pros:</strong> Clear valuation and equity structure from Day 1; no risk of debt solvency issues.</td>
</tr>
<tr class="even">
<td><strong>Cons:</strong> Debt remains outstanding if milestones missed (risk of lender control/insolvency). Valuation caps may suppress future valuations.</td>
<td><strong>Cons:</strong> More expensive/complex negotiation initially; immediate valuation required.</td>
</tr>
</tbody>
</table>
</section>
<section id="key-convertible-debt-terms" class="level3" data-number="15.9.2">
<h3 data-number="15.9.2" class="anchored" data-anchor-id="key-convertible-debt-terms"><span class="header-section-number">15.9.2</span> <strong>Key Convertible Debt Terms</strong></h3>
<ul>
<li><strong>The Discount:</strong> Allows noteholders to convert their principal plus interest into shares at a percentage discount (typically 10%–30%) to the price paid by the new investors in the qualifying round.<br>
</li>
<li><strong>Valuation Caps (Cap):</strong> An investor-favorable term setting a ceiling on the conversion price. If the future valuation exceeds the cap, the note converts at the price implied by the cap, giving the early investor a greater share of equity.<br>
</li>
<li><strong>Interest Rate:</strong> Since it is a loan, it accrues interest (typically 5%–12%), providing a minimum return.<br>
</li>
<li><strong>Conversion Mechanics:</strong> Must define the requirements for automatic conversion, typically a specific period (<strong>term</strong>) and a minimum capital raise (<strong>amount</strong>).<br>
</li>
<li><strong>Conversion in a Sale:</strong> Documents must specify what happens if the company is acquired before the debt converts. Options include repayment of principal plus interest, repayment plus a multiple (e.g., 2×–3×), or conversion to common-equivalent stock of the acquirer.<br>
</li>
<li><strong>Warrants:</strong> Sometimes issued instead of a discount, granting the right to purchase equity in the future.</li>
</ul>
</section>
<section id="alternative-approaches" class="level3" data-number="15.9.3">
<h3 data-number="15.9.3" class="anchored" data-anchor-id="alternative-approaches"><span class="header-section-number">15.9.3</span> <strong>Alternative Approaches</strong></h3>
<ul>
<li><strong>The SAFE (Simple Agreement for Future Equity):</strong> A popular instrument created by Y Combinator; it ignores valuation and has characteristics of equity, designed to avoid the legal complexity/risks associated with debt (like insolvency).<br>
</li>
<li><strong>KISS (Keep It Simple Security):</strong> Similar synthetic approach by 500 Startups.</li>
</ul>
</section>
</section>
<section id="the-capitalization-table" class="level2" data-number="15.10">
<h2 data-number="15.10" class="anchored" data-anchor-id="the-capitalization-table"><span class="header-section-number">15.10</span> <strong>The Capitalization Table</strong></h2>
<p>The <strong>Cap Table</strong> is a detailed spreadsheet summarizing ownership that founders must master.</p>
<section id="cap-table-calculation-example" class="level3" data-number="15.10.1">
<h3 data-number="15.10.1" class="anchored" data-anchor-id="cap-table-calculation-example"><span class="header-section-number">15.10.1</span> <strong>Cap Table Calculation Example</strong></h3>
<p>Calculating ownership is complicated by factors like the employee pool being defined post-money but calculated pre-money (diluting founders).</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Class</th>
<th>Shares</th>
<th>Price</th>
<th>Valuation</th>
<th>Percentage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Founders</td>
<td>2,000,000</td>
<td></td>
<td></td>
<td>46.67%</td>
</tr>
<tr class="even">
<td>Employee Pool</td>
<td>857,081</td>
<td></td>
<td></td>
<td>20.00%</td>
</tr>
<tr class="odd">
<td>Venture Investors</td>
<td>1,428,326</td>
<td>$3.50</td>
<td>$5,000,000</td>
<td>33.33%</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td>4,285,408</td>
<td></td>
<td>$15,000,000</td>
<td>100%</td>
</tr>
</tbody>
</table>
<p>In this example ($5M investment at $10M pre-money valuation with a 20% post-money option pool), the post-money ownership is VCs 33.33%, Employee Pool 20%, and Founders 46.67%.</p>
</section>
<section id="price-per-share-with-convertible-notes" class="level3" data-number="15.10.2">
<h3 data-number="15.10.2" class="anchored" data-anchor-id="price-per-share-with-convertible-notes"><span class="header-section-number">15.10.2</span> <strong>Price per Share with Convertible Notes</strong></h3>
<p>When convertible notes (CNs) convert into equity, three methods determine who bears the dilution from the CN conversion (principal, interest, and discount):</p>
<ol type="1">
<li><strong>Pre-Money Method:</strong> Fixes the agreed Pre-Money Valuation. Dilution is borne proportionately by both founders and the new Series A investors.<br>
</li>
<li><strong>Percentage-Ownership Method:</strong> Fixes the Series A investors’ target ownership percentage. Founders bear 100% of the dilution resulting from the note conversion.<br>
</li>
<li><strong>Dollars-Invested Method:</strong> Fixes the Post-Money Valuation to equal (Pre-Money + New Investment + Note Principal/Interest). Founders bear only the dilution from the CN discount; Series A investors keep their bargained-for valuation.</li>
</ol>
</section>
</section>
<section id="crowdfunding" class="level2" data-number="15.11">
<h2 data-number="15.11" class="anchored" data-anchor-id="crowdfunding"><span class="header-section-number">15.11</span> <strong>Crowdfunding</strong></h2>
<p>Crowdfunding has emerged as a powerful alternative financing approach.</p>
<section id="product-crowdfunding" class="level3" data-number="15.11.1">
<h3 data-number="15.11.1" class="anchored" data-anchor-id="product-crowdfunding"><span class="header-section-number">15.11.1</span> <strong>1. Product Crowdfunding</strong></h3>
<p>Used primarily for physical products (e.g., Kickstarter or Indiegogo). Companies solicit pre-orders or funds in exchange for tiered rewards. If the campaign fails to reach its target, funding does not occur. This acts as a validation mechanism for a <strong>Minimum Viable Product (MVP)</strong>.</p>
</section>
<section id="equity-crowdfunding" class="level3" data-number="15.11.2">
<h3 data-number="15.11.2" class="anchored" data-anchor-id="equity-crowdfunding"><span class="header-section-number">15.11.2</span> <strong>2. Equity Crowdfunding</strong></h3>
<p>Legalized by the <strong>JOBS Act</strong> in 2012, this allows companies to sell securities publicly. Compliance depends on the type of offering used, centered on two key securities concepts:</p>
<ul>
<li><strong>Accredited Investor:</strong> A person meeting specific net worth (1M) or income thresholds (200k/300k joint).<br>
</li>
<li><strong>General Solicitation:</strong> Public promotion or advertising of the fundraising, which historically was prohibited unless selling exclusively to accredited investors.</li>
</ul>
<p><strong>Title III Equity Crowdfunding:</strong> Allows sales to nonaccredited investors but is heavily regulated, capping raises at $1 million over 12 months, requiring a single funding portal/broker, and imposing high disclosure burdens.</p>
</section>
<section id="token-crowdfunding-icos" class="level3" data-number="15.11.3">
<h3 data-number="15.11.3" class="anchored" data-anchor-id="token-crowdfunding-icos"><span class="header-section-number">15.11.3</span> <strong>3. Token Crowdfunding (ICOs)</strong></h3>
<p>Mechanisms like Initial Coin Offerings (ICOs) or token offerings use digital currency to fund companies. This is an immature and highly speculative financing mechanism currently under intense scrutiny by the SEC.</p>
</section>
</section>
<section id="venture-debt" class="level2" data-number="15.12">
<h2 data-number="15.12" class="anchored" data-anchor-id="venture-debt"><span class="header-section-number">15.12</span> <strong>Venture Debt</strong></h2>
<p><strong>Venture Debt</strong> is a type of loan designed specifically for early-stage, high-growth companies that have already secured venture capital equity.</p>
<section id="the-role-and-players" class="level3" data-number="15.12.1">
<h3 data-number="15.12.1" class="anchored" data-anchor-id="the-role-and-players"><span class="header-section-number">15.12.1</span> <strong>The Role and Players</strong></h3>
<p>Venture debt complements equity, providing capital without dilution. The <strong>first rule of venture debt</strong> is that it follows equity; loans are underwritten based on the company’s existing VC support and access to future capital. Lenders include specialized banks (like Silicon Valley Bank) and debt funds.</p>
</section>
<section id="how-lenders-think-psor" class="level3" data-number="15.12.2">
<h3 data-number="15.12.2" class="anchored" data-anchor-id="how-lenders-think-psor"><span class="header-section-number">15.12.2</span> <strong>How Lenders Think (PSOR)</strong></h3>
<p>Lenders categorize loans based on the <strong>Primary Source of Repayment (PSOR)</strong>. For venture debt, the PSOR is the company’s ability to raise sufficient future equity capital.</p>
<ul>
<li><strong>Growth Capital Term Loan:</strong> The most common form of venture debt. Loans typically require repayment within 3–4 years, often beginning with a 6- to 12-month <strong>interest-only (I/O) period</strong>. Repayment then follows <strong>straight-line amortization</strong>.</li>
</ul>
</section>
<section id="key-terms" class="level3" data-number="15.12.3">
<h3 data-number="15.12.3" class="anchored" data-anchor-id="key-terms"><span class="header-section-number">15.12.3</span> <strong>Key Terms</strong></h3>
<ul>
<li><strong>Economic Terms:</strong> Include the interest rate (often variable), maturity date, warrants (giving the lender rights to purchase equity, typically 5%–10% of the loan amount), loan fees, and <strong>final payments</strong> (loan fees paid at maturity).<br>
</li>
<li><strong>Control Terms (Covenants):</strong> Legal restrictions used to manage repayment risk.
<ul>
<li><strong>Affirmative Covenants:</strong> Actions the company promises to take (e.g., maintain regulatory compliance).<br>
</li>
<li><strong>Negative Covenants:</strong> Actions the company promises <em>not</em> to take (e.g., incur certain debt, make excessive distributions).<br>
</li>
<li><strong>Material Adverse Change (MAC) Clause:</strong> A controversial provision allowing the lender to invoke default if a “material adverse change” in the business occurs.</li>
</ul></li>
</ul>
<p><strong>Application:</strong> The ultimate control mechanism is the <strong>Event of Default</strong>. Entrepreneurs must maintain transparency with lenders, especially if performance lags, as surprise is the enemy.</p>
</section>
</section>
<section id="how-venture-capital-funds-work" class="level2" data-number="15.13">
<h2 data-number="15.13" class="anchored" data-anchor-id="how-venture-capital-funds-work"><span class="header-section-number">15.13</span> <strong>How Venture Capital Funds Work</strong></h2>
<p>Understanding VC structure and incentives is crucial for managing the relationship.</p>
<section id="fund-structure-and-compensation" class="level3" data-number="15.13.1">
<h3 data-number="15.13.1" class="anchored" data-anchor-id="fund-structure-and-compensation"><span class="header-section-number">15.13.1</span> <strong>Fund Structure and Compensation</strong></h3>
<p>A VC firm typically consists of three entities:</p>
<ol type="1">
<li><strong>Management Company:</strong> Owned by senior partners; pays all operating expenses and staff salaries.<br>
</li>
<li><strong>Limited Partnership (LP) Vehicle (The Fund):</strong> Holds the capital committed by <strong>Limited Partners (LPs)</strong> (the investors in the fund).<br>
</li>
<li><strong>General Partnership (GP) Entity:</strong> Legal entity that manages the LP vehicle.</li>
</ol>
<p><strong>VC Compensation:</strong></p>
<ul>
<li><strong>Management Fee:</strong> Annual fee (typically 1.5%–2.5% of committed capital) paid by LPs to the management company to run operations.<br>
</li>
<li><strong>Carried Interest (Carry):</strong> The VC’s profit share, typically 20% of profits, paid only <em>after</em> the LPs have received back 100% of their committed capital. If a fund underperforms, VCs may be subject to a <strong>clawback</strong> (required to return profit distributions).</li>
</ul>
</section>
<section id="reserves-time-and-fiduciary-duties" class="level3" data-number="15.13.2">
<h3 data-number="15.13.2" class="anchored" data-anchor-id="reserves-time-and-fiduciary-duties"><span class="header-section-number">15.13.2</span> <strong>Reserves, Time, and Fiduciary Duties</strong></h3>
<ul>
<li><strong>Reserves:</strong> Capital allocated for follow-on investments in existing portfolio companies. Under-reserving can create friction if a company needs more capital than the VC has set aside.<br>
</li>
<li><strong>Time:</strong> The <strong>commitment period</strong> (usually 5 years) is the time VCs can make new investments. The <strong>life of the fund</strong>(typically 10 years) governs how long they manage investments. Pressure for liquidity increases toward the end of the fund’s life.<br>
</li>
<li><strong>Fiduciary Duties:</strong> VCs owe legal duties both to their LPs (to maximize fund return) and to the portfolio company’s shareholders (to act in the company’s best interest), which can lead to conflicts, especially during acquisition or financial distress negotiations.</li>
</ul>
</section>
</section>
<section id="negotiation-tactics" class="level2" data-number="15.14">
<h2 data-number="15.14" class="anchored" data-anchor-id="negotiation-tactics"><span class="header-section-number">15.14</span> <strong>Negotiation Tactics</strong></h2>
<p>Venture negotiation is unique because it is a <strong>multiplay game</strong> (a long-term relationship), not a <strong>single-play game</strong> (one-time transaction).</p>
<section id="core-negotiation-principles" class="level3" data-number="15.14.1">
<h3 data-number="15.14.1" class="anchored" data-anchor-id="core-negotiation-principles"><span class="header-section-number">15.14.1</span> <strong>Core Negotiation Principles</strong></h3>
<ol type="1">
<li><strong>Achieve a Win-Win:</strong> Aim for a result where both parties feel the outcome is fair, ensuring the long-term relationship is preserved.<br>
</li>
<li><strong>Preparation (BATNA):</strong> The single biggest mistake is lack of preparation. Determine your <strong>BATNA (Best Alternative to Negotiated Agreement)</strong>—your backup plan if you walk away.<br>
</li>
<li><strong>Leverage:</strong> The best leverage is having <strong>multiple, competing term sheets</strong>. Never reveal the names of other VCs you are negotiating with.<br>
</li>
<li><strong>Style:</strong> Understand negotiation personalities (Bully, Technocrat, Nice Guy, etc.) and adapt your approach. Favor transparency and clear communication.<br>
</li>
<li><strong>Focus:</strong> Concentrate energy almost exclusively on <strong>Economics and Control</strong>. Ancillary terms (e.g., Registration Rights) should be conceded quickly to build goodwill.<br>
</li>
<li><strong>Pacing:</strong> Never offer the first term sheet or price. Once you have a term sheet, try to control the pace of the ensuing negotiation.<br>
</li>
<li><strong>Lawyers:</strong> Your lawyer is a reflection of you; choose one who is effective but reasonable.</li>
</ol>
</section>
</section>
<section id="raising-money-the-right-way" class="level2" data-number="15.15">
<h2 data-number="15.15" class="anchored" data-anchor-id="raising-money-the-right-way"><span class="header-section-number">15.15</span> <strong>Raising Money the Right Way</strong></h2>
<p>Rookie mistakes to avoid when approaching VCs:</p>
<ul>
<li><strong>Don’t be a Machine:</strong> Fundraising is personal; VCs want to fall in love with the entrepreneurs.<br>
</li>
<li><strong>Don’t Ask for an NDA:</strong> VCs receive too many plans and avoid NDAs to prevent conflicts with future investments.<br>
</li>
<li><strong>Don’t Email Carpet-Bomb VCs:</strong> Mass mailings signal laziness and often result in immediate dismissal.<br>
</li>
<li><strong>No Often Means No:</strong> Respect a rejection; persistent follow-ups rarely change the outcome.<br>
</li>
<li><strong>Don’t Be a Solo Founder:</strong> VCs typically fund teams, believing execution (Grade A team) is more important than the idea.<br>
</li>
<li><strong>Don’t Overemphasize Patents:</strong> For software companies, patents are defensive weapons, not the foundation of the business.<br>
</li>
<li><strong>Don’t Be Silent If You Witness Bad Behavior:</strong> Speak up about bad behavior (e.g., sexual harassment) in the ecosystem.</li>
</ul>
</section>
<section id="issues-at-different-financing-stages" class="level2" data-number="15.16">
<h2 data-number="15.16" class="anchored" data-anchor-id="issues-at-different-financing-stages"><span class="header-section-number">15.16</span> <strong>Issues at Different Financing Stages</strong></h2>
<p>The dynamics of negotiation and deal terms shift significantly depending on the company stage:</p>
<ul>
<li><strong>Seed Deals (Pre-A):</strong> Often use Convertible Debt or SAFEs. Lowest legal costs and usually involve less contentious negotiation. The primary risk is setting a valuation too high, leading to a problematic down round later.<br>
</li>
<li><strong>Early Stage (Series A):</strong> Precedent is highly important; terms established here often carry through subsequent rounds. Entrepreneurs should fight to ensure all preferred stockholders vote together as a <strong>single class</strong> for protective provisions to simplify future governance.<br>
</li>
<li><strong>Mid and Late Stages (Series B+):</strong> Control becomes amplified; managing board composition (to avoid an oversized board) is crucial. Valuation maximization is dangerous if it comes with significant <strong>structure</strong> (excessive control or economic demands like guaranteed multiples) that limits future exit flexibility. Later-stage VCs often require final investment committee approval <em>after</em> the term sheet is signed.</li>
</ul>
</section>
<section id="letters-of-intent-the-other-term-sheet" class="level2" data-number="15.17">
<h2 data-number="15.17" class="anchored" data-anchor-id="letters-of-intent-the-other-term-sheet"><span class="header-section-number">15.17</span> <strong>Letters of Intent: The Other Term Sheet</strong></h2>
<p>The <strong>Letter of Intent (LOI)</strong>, or Indication of Interest (IOI), is the term sheet used by an acquirer to propose buying the company. It is generally nonbinding, except for clauses like the <strong>no-shop agreement</strong>.</p>
<section id="deal-structure-and-price" class="level3" data-number="15.17.1">
<h3 data-number="15.17.1" class="anchored" data-anchor-id="deal-structure-and-price"><span class="header-section-number">15.17.1</span> <strong>Deal Structure and Price</strong></h3>
<p>Acquisition negotiations are competitive and assume a fixed pie. Price is often complicated by contingent components:</p>
<ul>
<li><strong>Escrow (Holdback):</strong> Money set aside (typically 10%–20% of consideration for 12–24 months) to cover breaches of <strong>representations and warranties (Reps and Warranties)</strong>.<br>
</li>
<li><strong>Working Capital Adjustment:</strong> Adjusts the final purchase price based on a minimum level of working capital delivered at closing.<br>
</li>
<li><strong>Earn-outs:</strong> A portion of the purchase price paid only if specific milestones are met post-acquisition; usually a tool for the acquirer to underpay at closing.<br>
</li>
<li><strong>Management Retention Pool:</strong> Money explicitly carved out of the purchase price to incentivize key management to stay post-acquisition.</li>
</ul>
</section>
<section id="asset-deal-vs.-stock-deal" class="level3" data-number="15.17.2">
<h3 data-number="15.17.2" class="anchored" data-anchor-id="asset-deal-vs.-stock-deal"><span class="header-section-number">15.17.2</span> <strong>Asset Deal vs.&nbsp;Stock Deal</strong></h3>
<ul>
<li><strong>Stock Deal (Seller Preferred):</strong> Acquirer buys the entire corporate entity, which disappears into the buyer’s structure. Simpler for the seller.<br>
</li>
<li><strong>Asset Deal (Buyer Preferred):</strong> Acquirer buys only specified assets, leaving liabilities (warts) behind. Forces the selling entity to deal with winding down the company.</li>
</ul>
</section>
<section id="key-loi-clauses" class="level3" data-number="15.17.3">
<h3 data-number="15.17.3" class="anchored" data-anchor-id="key-loi-clauses"><span class="header-section-number">15.17.3</span> <strong>Key LOI Clauses</strong></h3>
<ul>
<li><strong>Form of Consideration:</strong> Cash is king. If stock is offered (public or private), its liquidity, valuation, and the buyer’s underlying capital structure must be scrutinized.<br>
</li>
<li><strong>Assumption of Stock Options:</strong> Must clearly define how employee stock options will be handled (e.g., cashed out, rolled into new options).<br>
</li>
<li><strong>No-Shop Clause:</strong> <strong>Binding</strong> provision preventing the seller from soliciting or negotiating with other buyers for a specific period (e.g., 45–60 days).<br>
</li>
<li><strong>Breakup Fee:</strong> Penalty paid if the seller breaches the no-shop clause and closes a deal with a third party.<br>
</li>
<li><strong>Shareholder Representatives:</strong> An individual or firm (like SRS Acquiom) designated to manage post-closing matters, such as escrow claims and earn-outs, on behalf of the selling shareholders.</li>
</ul>
</section>
</section>
<section id="how-to-engage-an-investment-banker" class="level2" data-number="15.18">
<h2 data-number="15.18" class="anchored" data-anchor-id="how-to-engage-an-investment-banker"><span class="header-section-number">15.18</span> <strong>How to Engage an Investment Banker</strong></h2>
<p>Investment bankers are generally supported in an <strong>acquisition context</strong> but discouraged in early-stage financings.</p>
<section id="why-hire-a-banker" class="level3" data-number="15.18.1">
<h3 data-number="15.18.1" class="anchored" data-anchor-id="why-hire-a-banker"><span class="header-section-number">15.18.1</span> <strong>Why Hire a Banker?</strong></h3>
<ol type="1">
<li><strong>Maximize Exit Value:</strong> Expose the company to the largest universe of logical acquirers (often 50+ contacts).<br>
</li>
<li><strong>Workload Management:</strong> Bankers manage logistical tasks (initial calls, scheduling, data room).<br>
</li>
<li><strong>Buffer:</strong> Act as a negotiation buffer, preserving the relationship between seller management and the acquirer.</li>
</ol>
</section>
<section id="negotiating-the-engagement-letter" class="level3" data-number="15.18.2">
<h3 data-number="15.18.2" class="anchored" data-anchor-id="negotiating-the-engagement-letter"><span class="header-section-number">15.18.2</span> <strong>Negotiating the Engagement Letter</strong></h3>
<p>The contract should be reviewed extensively by lawyers and the board. Key negotiation points include:</p>
<ol type="1">
<li><strong>Scope of Work:</strong> Clearly defines the assignment (e.g., sell-side or <strong>dual-track funding and M&amp;A engagement</strong>).<br>
</li>
<li><strong>Success Fee:</strong> The majority of compensation, calculated as a percentage of gross proceeds. Often scaled to incentivize higher exit values. Banker should agree to accept the same form of consideration (stock/cash) as shareholders.<br>
</li>
<li><strong>Retainer and Expenses:</strong> Nonrefundable monthly fee (retainer) that should be deductible against the success fee; out-of-pocket expenses should be capped and reasonable.<br>
</li>
<li><strong>Key Person Provision:</strong> Allows the company to terminate the engagement if the specific banker leaves the firm.</li>
</ol>
</section>
</section>
<section id="why-do-term-sheets-even-exist" class="level2" data-number="15.19">
<h2 data-number="15.19" class="anchored" data-anchor-id="why-do-term-sheets-even-exist"><span class="header-section-number">15.19</span> <strong>Why Do Term Sheets Even Exist?</strong></h2>
<p>While some VCs are comfortable with simple agreements, the term sheet and definitive documents are necessary for multiple reasons.</p>
<section id="constraining-behavior-and-aligning-incentives" class="level3" data-number="15.19.1">
<h3 data-number="15.19.1" class="anchored" data-anchor-id="constraining-behavior-and-aligning-incentives"><span class="header-section-number">15.19.1</span> <strong>1. Constraining Behavior and Aligning Incentives</strong></h3>
<p>Contracts help align the sometimes divergent interests of VCs, founders, and employees. VCs rely on written contracts because courts generally offer VCs no benefit of the doubt in conflicts. Good contracts mitigate the potential for bad behavior.</p>
</section>
<section id="transaction-costs" class="level3" data-number="15.19.2">
<h3 data-number="15.19.2" class="anchored" data-anchor-id="transaction-costs"><span class="header-section-number">15.19.2</span> <strong>2. Transaction Costs</strong></h3>
<p>Contracts minimize current and future costs (time and money) associated with defining the relationship.</p>
</section>
<section id="agency-costs-and-information-asymmetry" class="level3" data-number="15.19.3">
<h3 data-number="15.19.3" class="anchored" data-anchor-id="agency-costs-and-information-asymmetry"><span class="header-section-number">15.19.3</span> <strong>3. Agency Costs and Information Asymmetry</strong></h3>
<p>Contracts mitigate <strong>agency costs</strong> (costs resulting from an agent acting on a principal’s behalf—e.g., a CEO delaying a necessary sale to save his job) and <strong>information asymmetry</strong> (where one party knows more than the other).</p>
</section>
<section id="reputation-constraints" class="level3" data-number="15.19.4">
<h3 data-number="15.19.4" class="anchored" data-anchor-id="reputation-constraints"><span class="header-section-number">15.19.4</span> <strong>4. Reputation Constraints</strong></h3>
<p>The small, interconnected venture capital ecosystem means reputation matters significantly, imposing non-legal constraints on behavior. However, this is not a substitute for formal contracts.</p>
</section>
</section>
<section id="legal-things-every-entrepreneur-should-know" class="level2" data-number="15.20">
<h2 data-number="15.20" class="anchored" data-anchor-id="legal-things-every-entrepreneur-should-know"><span class="header-section-number">15.20</span> <strong>Legal Things Every Entrepreneur Should Know</strong></h2>
<section id="intellectual-property-ip-1" class="level3" data-number="15.20.1">
<h3 data-number="15.20.1" class="anchored" data-anchor-id="intellectual-property-ip-1"><span class="header-section-number">15.20.1</span> <strong>Intellectual Property (IP)</strong></h3>
<p>IP must be protected from co-founder disputes or claims from previous employers.</p>
<ul>
<li><strong>PIIAs:</strong> Mandate PIIAs for everyone touching the IP.<br>
</li>
<li><strong>Patents:</strong> Provide a 20-year monopoly. Costly (up to $25,000 for a full application).<br>
</li>
<li><strong>Trademarks:</strong> Protect distinctive names or symbols (branding).</li>
</ul>
</section>
<section id="corporate-and-employment-structure" class="level3" data-number="15.20.2">
<h3 data-number="15.20.2" class="anchored" data-anchor-id="corporate-and-employment-structure"><span class="header-section-number">15.20.2</span> <strong>Corporate and Employment Structure</strong></h3>
<ul>
<li><strong>Corporate Structure:</strong> Start as a <strong>C Corp</strong> because it is the standard for VC investment and avoids complexities associated with S Corps or LLCs when granting equity.<br>
</li>
<li><strong>Employment Issues:</strong> Use <strong>at-will employment</strong> contracts. Consult an employment lawyer for all founder/executive departures to settle equity and IP cleanly.<br>
</li>
<li><strong>Consultants vs.&nbsp;Employees:</strong> Companies must be careful not to misclassify long-term service providers as consultants to avoid wage/hour obligations.</li>
</ul>
</section>
<section id="stock-and-tax-issues" class="level3" data-number="15.20.3">
<h3 data-number="15.20.3" class="anchored" data-anchor-id="stock-and-tax-issues"><span class="header-section-number">15.20.3</span> <strong>Stock and Tax Issues</strong></h3>
<ul>
<li><strong>Accredited Investors:</strong> VCs traditionally sell securities only to accredited investors to maintain regulatory compliance.<br>
</li>
<li><strong>Section 409A Valuations:</strong> IRS regulation governing the <strong>strike price</strong> of stock options. Companies must obtain professional, periodic valuations to ensure a “safe harbor”.<br>
</li>
<li><strong>83(b) Elections:</strong> Tax election that founders/early employees must file with the IRS within 30 days of receiving restricted stock (Founders’ Stock). This allows the recipient to pay taxes upfront based on the current low valuation, securing favorable long-term capital gains tax rates later.<br>
</li>
<li><strong>Founders’ Stock:</strong> Common stock sold at formation for a nominal price. Must be subject to vesting.<br>
</li>
<li><strong>Compensating Service Providers:</strong> Equity (stock grants or <strong>stock options</strong>) is typically granted via a Stock Option Plan and subject to vesting to retain service providers.</li>
</ul>
<hr>
</section>
</section>
<section id="final-comprehensive-summary" class="level2" data-number="15.21">
<h2 data-number="15.21" class="anchored" data-anchor-id="final-comprehensive-summary"><span class="header-section-number">15.21</span> <strong>Final Comprehensive Summary</strong></h2>
<p><em>Venture Deals</em> is essential reading for entrepreneurs, instructing them to approach venture capital financing not as a mysterious legal hurdle, but as a strategic negotiation centered on long-term partnership viability.</p>
<p>The fundamental framework of any deal rests on <strong>Economics and Control</strong>. Economically, the key goal is establishing a high <strong>Valuation</strong> and minimizing preferential investor rights that could disproportionately disadvantage founders in a low-value <strong>liquidation event</strong>. This involves negotiating the <strong>Liquidation Preference</strong> (aiming for 1× nonparticipating preferred) and determining the size of the <strong>Employee Option Pool</strong>. Founders must understand how <strong>Antidilution</strong>mechanisms (preferably broad-based weighted average) protect investors from down rounds.</p>
<p>In terms of control, entrepreneurs must secure a balanced <strong>Board of Directors</strong> and limit <strong>Protective Provisions</strong> (veto rights) to essential actions only. They must also understand mechanisms designed to align shareholder behavior, like <strong>Drag-Along Agreements</strong> (facilitating sales) and <strong>Pay-to-Play</strong> clauses (forcing participation in future rounds). Negotiation leverage is maximized through transparency and generating multiple competing offers (BATNA).</p>
<p>For early-stage companies, <strong>Convertible Debt</strong> offers a simpler alternative to equity by using a <strong>Discount</strong> and/or <strong>Valuation Cap</strong> to defer the difficult task of setting a price. Regardless of the funding mechanism, meticulous due diligence preparation (Delaware C Corp structure, comprehensive documentation, and clear IP assignment via PIAs) and hiring a sophisticated legal counsel are non-negotiable precursors to success. Finally, recognizing that VCs are motivated by their own fund structures (management fees, carry, reserves) is key to managing the relationship effectively over the long term.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chapter14.html" class="pagination-link" aria-label="Financial Intelligence for Entrepreneurs">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Financial Intelligence for Entrepreneurs</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./chapter16.html" class="pagination-link" aria-label="Emotional Agility">
        <span class="nav-page-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Emotional Agility</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>